### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chuck-sys** [cheukyin699/tower-defence#1]
### Implementations:
- [ ] Gatling gun
- [ ] Mortar tower
### Misc.:
- [ ] Replace Sniper Tower artwork
- [ ] An upgrades system
### Implementations:
- [ ] Black Enemy
- [ ] Metal Enemy
- [ ] Titanium Enemy
- [ ] Camouflaged Enemies
- [ ] Regenerative Enemies
## Maps:
- [ ] 2 more single-player maps
- [ ] 1 multiplayer map
## Multiplayer:
- [ ] Server as relay
- [ ] Chat
- [ ] Basic functionality(ies)
## Musics/Clips
- [ ] Music when in playing mode
- [ ] SFX for shooting/hitting
